### ISSUE TITLE
Extract private keys from repo

### ISSUE THREAD

**Issue by iamclaytonray** [serverless/serverless-graphql#156]
Hey... I'm not sure if the keys in `config/` are real but I recommend ignoring the entire `config` directory from git. Maybe make an example config directory and replace those keys with placeholders. This also helps with DX because I know I personally would think those were my keys due to my horrible memory. If this is something you'd accept a PR for, let me know and I'll shoot it over right away

**Comment by sid88in** [comment]
@iamclaytonray thanks for your feedback. I agree that we should iterate on how configs are stored and read in the framework. The configs given in the repo can be used to kickstart the project quickly so that people don't have to go through the pain of creating their own twitter consumer and secret key. Feel free to create your own keys if you want. 

Having said that if you have a better way to handle configs, please feel free to create a PR and we can review (I am not 100% sure if I understand the solution you are proposing).

**Comment by iamclaytonray** [comment]
I’ll hack something together when I get home

**Comment by iamclaytonray** [comment]
I’ll hack something together when I get home

**Comment by iamclaytonray** [comment]
Whoops, sorry 🙄😅
