### ISSUE TITLE
Problems running AppSync example

### ISSUE THREAD

**Issue by maziarz** [serverless/serverless-graphql#249]
First of, great job with integrating AppSync! I tried to follow the README with starting up the AppSync example, but it is not going as expected:

```
serverless-graphql/app-backend/appsync/dynamo/$ yarn start
Installation complete!
Dynamodb Local Started, Visit: http://localhost:8000/shell
Serverless: DynamoDB - created table users
Seed running complete for table: users
Serverless: Starting Offline: dev/us-east-1.

Serverless: Offline listening on http://localhost:3000
```

Followed by:

```
serverless-graphql/app-client/appsync-client$ yarn start
Compiled successfully!

You can now view app-client in the browser.

  Local:            http://localhost:3001/
  On Your Network:  http://192.168.1.34:3001/

Note that the development build is not optimized.
To create a production build, use yarn build.
```

When the website is automatically launched i seen an error: `Network error: Failed to fetch``

<img width="453" alt="skaermbillede 2018-01-04 kl 17 57 13" src="https://user-images.githubusercontent.com/15786116/34574775-bfe1ad62-f178-11e7-9751-cbff9b5a1289.png">

**Comment by sid88in** [comment]
@maziarz you are getting this error because there is no server running on local when you run appsync client. In config/security.env.local REACT_APP_GRAPHQL_ENDPOINT=http://localhost:4000/graphql
Right now appsync doesn't support running on local 

For instance, if you run app-backend/dynamodb> yarn start and then run appsync-client it will work. 

So, you will first need to deploy appsync on aws, make sure the endpoint works and then replace that endpoint in config/security.env.local. 

After that, if you get error related to authentication, it might be because of passing Cognito user pool authentication header. We are working to simplify that using open PR - AWS Amplify. Also, you might want to try modheader to make it work for now. 

P.S: We are in the process of improving documentation for appsync and add remaining features. Feel free to contribute :)

**Comment by maziarz** [comment]
Are you currently working on deploying AppSync API's from either the SDK or CLI? I am planning to do that myself..

**Comment by sid88in** [comment]
This boilerplate allows you to deploy appsync automatically using JS SDK for instance - https://github.com/serverless/serverless-graphql/blob/master/app-backend/appsync/dynamo/deploy-dynamo.js

Ideally, you would want to use something which is reproducible, scalable and easy to deploy.

**Comment by maziarz** [comment]
Awesome example! Is it possible to find you somewhere on Gitter or Slack to discuss some things?

**Comment by sid88in** [comment]
You can contact me on twitter @sidg_sid
