### ISSUE TITLE
Tests Needed

### ISSUE THREAD

**Issue by ac360** [serverless/serverless-graphql#28]
We need some basic tests for GraphQL User CRUD operations.

**Comment by laardee** [comment]
Everyone is fighting over this one. :smile: I can give a try, though I haven't work with GraphQL much. Unless you are in a hurry, I think it will take couple days for me to get started.

Do you have any preference how tests should be done (mocha with chai or something else, etc.)?

**Comment by ac360** [comment]
Thanks @laardee!  We're all still new to GraphQL :)  Tests done in mocha or chai are totally fine.  I really appreciate your help here.

**Comment by nikgraf** [comment]
@laardee any progress? I would be happy to help out here over the weekend …

**Comment by laardee** [comment]
There is couple minor things left that I need to fix, otherwise I'm almost done with writing the tests. I'll try to open PR today.

**Comment by laardee** [comment]
I opened a PR so that it is easier to discuss. 

It includes following tests:
* create user
* get users
* get one user
* login fails because of incorrect username
* login fails because of incorrect password
* successful login
* fails to update user with bad token
* successfully updates user
* fails to delete user with bad token
* successfully deletes user
* get empty users response after deleting

There is still an issue with create user test. User is successfully created, but then function tries to invoke `timeout` function with lambda.invoke, which causes following error. 

```
{ data: { createUser: null },
  errors: 
   [ { [Error: Function not found: arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:serverless-boilerplate-timeout:dev]
       message: 'Function not found: arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:serverless-boilerplate-timeout:dev',
```

After user creation it tries to trigger `arn:aws:lambda:us-east-1:XXXXXXXXXXXX:function:serverless-boilerplate-timeout:dev` function, but as it is executed locally, it can't do that. Should the [invoke.js](https://github.com/serverless/serverless-graphql/blob/master/back/api/lib/invoke.js) be modified to function differently when it is executed when environment variable IS_OFFLINE is true? Or should I just ignore that timeout error in the test and catch other errors? Do you have any suggestions? @ac360 @nikgraf
